pdf/pdf_add_bookmarks.go, pdf/pdf_add_images.go, pdf/pdf_add_images_fast.go, pdf/pdf_crop.go, pdf/pdf_list_bookmarks.go, pdf/pdf_rotate.go, pdf/pdf_watermark_image.go
Related to higher level outline handling (UD-26).  In addition, performed more rigorous testing and updated all the examples.
=> Updated outlines and examples tested more

pdf/analysis/pdf_all_objects.go, pdf/analysis/pdf_describe.go
This helps me develop with unidoc. I use it to print out the contents of PDF files
=> added pdf_all_objects.go

pdf/security/pdf_check_permissions.go, pdf/security/pdf_protect.go
* Update `pdf_check_permissions` example
* Update `pdf_protect` example
=> Update examples for the new encryption api

pdf/testing/pdf_passthrough_bench.go
=> Added optimization parameters

pdf/forms/pdf_form_fill_json.go
Added pdf_form_fill_json.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unidoc-examples/26)
=> Loading and filling forms via JSON

pdf/forms/pdf_form_add.go
=> Matching branch for unidoc v3-reduce-fonts-exports

pdf/signatures/README.md, pdf/signatures/pdf_sign_appearance.go, pdf/signatures/pdf_sign_external.go, pdf/signatures/pdf_sign_generate_keys.go, pdf/signatures/pdf_sign_hsm_pkcs11.go, pdf/signatures/pdf_sign_pkcs12.go, pdf/signatures/pdf_sign_validate.go
- pdf_sign_generate_keys.go
- pdf_sign_pkcs12.go
- pdf_sign_external.go
- pdf_sign_appearance.go
- pdf_sign_validate.go
=> Add more signing examples

pdf/signatures/README.md, pdf/signatures/pdf_sign_appearance.go, pdf/signatures/pdf_sign_external.go, pdf/signatures/pdf_sign_generate_keys.go, pdf/signatures/pdf_sign_hsm_pkcs11.go, pdf/signatures/pdf_sign_pkcs12.go, pdf/signatures/pdf_sign_validate.go
- Example for digital signature via HSM PKCS11
=> Examples for Digital Signatures

pdf/compress/pdf_optimize.go
=> Add PDF compression example

.gitignore, build_examples.sh, go.mod
=> add build_examples.sh build script

image/pdf_extract_images.go
=> Update image example to use extractor

analysis/pdf_summarize_images.go
Program by Peter Williams an analysis tool for checking image objects in PDF
=> Add pdf_summarize_images.go 

go.mod, go.sum, text/pdf_search_replace_advanced.go
=> Add more advanced text search and replace example

go.mod, go.sum, jbig2/jbig2_decompress.go
=> Updated go.mod unipdf to v3.6.0. Minor change to jbig2 decompress.

signatures/pdf_sign_generate_keys.go
Addresses https://github.com/unidoc/unipdf-examples/issues/106.
=> Update pdf_sign_generate_keys.go example

text/pdf_search_replace.go
=> update wrong operator symbol

text/pdf_tables.go
This is a simple command line wrapper around the table extraction code
=> Table extraction example.

signatures/README.md, signatures/ltv/README.md, signatures/ltv/pdf_ltv_enable_signed_file.go, signatures/ltv/pdf_sign_ltv_extra_revision.go, signatures/ltv/pdf_sign_ltv_one_revision.go, signatures/ltv/pdf_sign_ltv_timestamp_revision.go
- Adds LTV examples
- Updates modules for unipdf v3.14.0
=> Examples for UniPDF v3.14.0

render/jpeg2k/lib_jpeg2k_encoder.go
This update showcase how to handle `ColorSpace` info from the pdf document to overwrite JPEG2000 image's color space information.
=> Update jpx encoder callback example to handle document ColorSpace

advanced/pdf_grayscale_transform.go, annotations/pdf_annotate_add_ellipse.go, annotations/pdf_annotate_add_line.go, annotations/pdf_annotate_add_rectangle.go, annotations/pdf_annotate_add_text.go, forms/pdf_form_add.go, go.mod, go.sum, pages/pdf_crop.go, pages/pdf_page_rotate.go
This update shows examples of using `PageProcessCallback` introduced in UniPDF v3.21.0.
=> Using PageProcessCallback

go.mod, go.sum, javascript/pdf_add_javascript_docopen.go
Requires a new method in UniPDF, PR in preparation.
=> Example for adding javascript action on PDF open

license/README.md
This PR closes #218 -> the link is updated and now works
I see that my branching name is not consistent with what you usually have, but I suppose to fix that I would need a `UP-xxx` issue number.
I am up for fixing that too, not sure how to get the official project issue created though.
=> update the link to the offline license example

text/pdf_highlight_text.go, text/pdf_search_replace_advanced.go
I've noticed that in couple of old examples init() function with metered key setting is missing and added it.
=> Added metered key setting to a couple of examples where it was missing.

go.mod, go.sum, pdfa/pdfa3_apply_standard.go, pdfa/pdfa3_validate_standard.go
Add code examples for PDF/A-3 validation introduced in UniPDF v3.58
=> [US-397] Add PDF/A-3 examples

forms/pdf_form_fill_custom_font.go
This PR updates the example to prevent extraction issue like https://unidoc.atlassian.net/browse/US-386
=> [US-386] Update Flattening  with Custom Font Example 

.github/workflows/go.yml, go.mod, go.sum, render/jpeg2k/lib_jpeg2k_encoder.go
To solve issue the build fails on github-actions
```
fatal error: 'wand/MagickWand.h' file not found
#include <wand/MagickWand.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
xargs: bash: exited with status 255; aborting
```
=> update imagick version to v3

go.mod, go.sum, image/README.md, image/pdf_remove_watermark_image.go, image/pdf_watermark_image.go
Added example how to remove watermark.
Changed add watermark example so it is now using the unipdf function AddWatermarkImage() instead of custom drawing.
=> [US-800] Watermark examples.
